"""add recommendation

Revision ID: ac614c995caa
Revises: db7f84812e5d
Create Date: 2024-02-08 14:04:22.446411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac614c995caa'
down_revision: Union[str, None] = 'db7f84812e5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_recommendation',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('items', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_recommendation')
    # ### end Alembic commands ###
