"""add movie rating

Revision ID: fe34b55fdf79
Revises: 5329683b4fd7
Create Date: 2024-02-11 13:09:58.299529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe34b55fdf79'
down_revision: Union[str, None] = '5329683b4fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie_ratings', sa.Column('action', sa.Integer(), nullable=False))
    op.add_column('movie_ratings', sa.Column('adventure', sa.Integer(), nullable=False))
    op.add_column('movie_ratings', sa.Column('animation', sa.Integer(), nullable=False))
    op.add_column('movie_ratings', sa.Column('biography', sa.Integer(), nullable=False))
    op.add_column('movie_ratings', sa.Column('comedy', sa.Integer(), nullable=False))
    op.add_column('movie_ratings', sa.Column('crime', sa.Integer(), nullable=False))
    op.add_column('movie_ratings', sa.Column('drama', sa.Integer(), nullable=False))
    op.add_column('movie_ratings', sa.Column('family', sa.Integer(), nullable=False))
    op.add_column('movie_ratings', sa.Column('fantasy', sa.Integer(), nullable=False))
    op.add_column('movie_ratings', sa.Column('film_noir', sa.Integer(), nullable=False))
    op.add_column('movie_ratings', sa.Column('history', sa.Integer(), nullable=False))
    op.add_column('movie_ratings', sa.Column('horror', sa.Integer(), nullable=False))
    op.add_column('movie_ratings', sa.Column('music', sa.Integer(), nullable=False))
    op.add_column('movie_ratings', sa.Column('musical', sa.Integer(), nullable=False))
    op.add_column('movie_ratings', sa.Column('mystery', sa.Integer(), nullable=False))
    op.add_column('movie_ratings', sa.Column('romance', sa.Integer(), nullable=False))
    op.add_column('movie_ratings', sa.Column('sci_fi', sa.Integer(), nullable=False))
    op.add_column('movie_ratings', sa.Column('sport', sa.Integer(), nullable=False))
    op.add_column('movie_ratings', sa.Column('thriller', sa.Integer(), nullable=False))
    op.add_column('movie_ratings', sa.Column('war', sa.Integer(), nullable=False))
    op.add_column('movie_ratings', sa.Column('western', sa.Integer(), nullable=False))
    op.drop_column('movie_ratings', 'genres')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie_ratings', sa.Column('genres', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('movie_ratings', 'western')
    op.drop_column('movie_ratings', 'war')
    op.drop_column('movie_ratings', 'thriller')
    op.drop_column('movie_ratings', 'sport')
    op.drop_column('movie_ratings', 'sci_fi')
    op.drop_column('movie_ratings', 'romance')
    op.drop_column('movie_ratings', 'mystery')
    op.drop_column('movie_ratings', 'musical')
    op.drop_column('movie_ratings', 'music')
    op.drop_column('movie_ratings', 'horror')
    op.drop_column('movie_ratings', 'history')
    op.drop_column('movie_ratings', 'film_noir')
    op.drop_column('movie_ratings', 'fantasy')
    op.drop_column('movie_ratings', 'family')
    op.drop_column('movie_ratings', 'drama')
    op.drop_column('movie_ratings', 'crime')
    op.drop_column('movie_ratings', 'comedy')
    op.drop_column('movie_ratings', 'biography')
    op.drop_column('movie_ratings', 'animation')
    op.drop_column('movie_ratings', 'adventure')
    op.drop_column('movie_ratings', 'action')
    # ### end Alembic commands ###
